language: python
python:
- '2.7'
sudo: false
cache:
- directories:
  - $HOME/.cache/pip
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- pip install -U pip wheel codecov
- pip install -r requirements/test.txt
script:
- make validate
after_success:
- codecov
deploy:
  provider: pypi
  user: edx
  password:
    secure: od0JHgfyWdUSI9jBpeIa18Y3FUAPCBCSUlwq4moJWJa2NCawbZ7utDJQeZ4ra7su2UsCUESvpqlUegEEaER/Pfd7rCnO6HsP68HVORMuCPjmIpAenBFLsgHBLmybvjXQNQk0BCfUhtGvsLzZwF2kG8/HAj+YYoSJgKlDx946kRZQaiwqlkY19ZsGy8iiL529sAibfh7OTiFRwpIIkEnH9wPuiZT8uD2ykzjSmGA+iyZPopyrESYWCL1GuooE5eg0yvR9aGPRVmrLrpG9T8Upg6zAWwsM5uumsFTiwqO704XdL6JZGzaiLi/ISjeuy9evFrI2XPSZGE7dSzmjl7S56GiPHeyvh8+VAYIMCNR4oAIxIWQJ0PJXJcxDJA0D3py0Ed+vq7R2I5lAW5sEV2AKQSIc+hEKQjfeAW8xVZNLBh0s4eW+d9NYSkB9E9aOcQ6KA1APE7J3hE+Zf/oa/Fwzd0LaYc1uTFccDqBMr6WGOIB8Zbrw+c4XeizebdS05ptHNGjnQCTjGo+to6G/Pkiwc1H4cbEZBM8ug8VswK30aDTTDXgv/SJGBnelsZzy0ahyiSbKWHG9V5zosqmh/U/QpenCv2kGO9nUCJsRUQI8znOxmJtcf69PqT//yiIilmhNa/xVmbOnCMEPDEzCiQ1nyH1XYVIr5dzS2/hScD1WqHQ=
  distributions: sdist bdist_wheel
  on:
    tags: true
